const namesarr = [
    "Приятная Lo-Fi музыка",
    "Другая версия Lo-Fi этой же музыки",
    "Lo-Fi Музыка для работы",
    "Lo-Fi музыка для расслабления",
    "Создателю нравится эта музыка",
    "Отлично подходит для работы",
    "Hatted by life itself",
    "Hyakka Ryouran",
    "Kawaki wo Ameku",
    "Monitoring",
    "Snow Fairy Story",
    "Snow Song Show",
    "Tynix",
    "Wildfire",
    "Yoidore Shirazu",
    "Haru",
    "Gotoubun no Katachi",
    "Masayume Chasing",
    "Oddloop",
    "VORACITY",
    "Gift",
    "Otonoke",
    "Belief",
    "Irokousui(feat.B-Lion)",
    "ReawakeR(feat.Coconut Dog)",
    "Po Jian",
    "風",
    "別れ",
    "Катюша",
    "ミライチズ",
    "IDOL",
    "Tokyo Autumn Session",
    "Ruler of my heart",
    "AiScReam",
    "Gonju"
];

const authors = [
    "Неизвестно",
    "Неизвестно",
    "Неизвестно",
    "Неизвестно",
    "Неизвестно",
    "Неизвестно",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Sati Akura",
    "Onsa Media",
    "Dima Lancaster",
    "Frederic",
    "Jackie-O",
    "Masayoshi Ooishi",
    "Creepy Nuts",
    "Sayaka Sasaki",
    "Jackie-O",
    "Tanri",
    "Sati Akura",
    "Hatsune Miku",
    "yoru no hitowarai",
    "Девочки и танки",
    "yoru no hitowarai",
    "YOASOBI",
    "Jackie-O feat. Sabi-tyan",
    "Melody Note, Kirio",
    "AiScReam",
    "Yoasobi"
];

 const categorys = [
  "Lo-Fi",
  "Lo-Fi",
  "Lo-Fi",
  "Lo-Fi",
  "Lo-Fi",
  "Lo-Fi",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Cover",
  "Песня",
  "Cover",
  "Песня",
  "Песня",
  "Песня",
  "Cover",
  "Cover",
  "Cover",
  "Песня",
  "Песня",
  "Песня",
  "Песня",
  "Песня",
  "Cover",
  "Cover",
  "Песня",
  "Песня"
];
export{
    namesarr, categorys, authors
}